language: node_js
os:
  - linux
  - osx
sudo: required
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
node_js:
  - "v6.0.0"
  - "v5.0.0"
  - "v4.0.0"
install:
  - npm install
script:
  - npm test
